### ISSUE TITLE
force user = %U with timemachine

### ISSUE THREAD

**Issue by bvarick** [ServerContainers/samba#115]
I'm trying to setup TimeMachine backups for multiple computers to my server. The main user of each of these computers has a UID of 1000, I want them to each map to a share with a different uid (2001, 2002, etc). I think `force user = %U` is what I'm looking for, what I think should work is this docker compose (note the `force user` part of the timemachine config):
```
version: '3'

services:
  samba:
    build: .
    image: ghcr.io/servercontainers/samba
    restart: always
    ports:
      - 445:445

    environment:
      MODEL: 'TimeCapsule'
      AVAHI_NAME: TimeMachine

      SAMBA_CONF_LOG_LEVEL: 3

      WSDD2_DISABLE: 1
      AVAHI_DISABLE: 1
#      NETBIOS_DISABLE: 1

      GROUP_family: 1500

      ACCOUNT_alice: "alice:2002:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:8846F7EAEE8FB117AD06BDD830B7586C:[U          ]:LCT-5FE1F7DF:"
      UID_alice: 2002
      GROUPS_alice: family

      ACCOUNT_bob: "bob:2003:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:8846F7EAEE8FB117AD06BDD830B7586C:[U          ]:LCT-5FE1F7DF:"
      UID_bob: 2003
      GROUPS_bob: family

      SAMBA_VOLUME_CONFIG_timemachine: "[TimeMachine]; path=/shares/timemachine/%U; valid users = alice, bob; force user = %U; guest ok = no; read only = no; browseable = yes; fruit:time machine = yes; fruit:time machine max size = 1500G"

    volumes:
      - /mnt/timemachine:/shares/timemachine

```
But it doesn't work. When I set a user to a UID of 1000, it works perfectly for that user, but I obviously can't set all the users to a UID of 1000. Any suggestions?
