### ISSUE TITLE
Samba Server not visible

### ISSUE THREAD

**Issue by braberli** [ServerContainers/samba#117]
I am sure it is not an issue but a problem "in front of the computer":

I created a container using docker compose which is running smoothly. Accessing the container via docker excec and also the logs show me that everything is running nicely. But I cannot find, see or access the shares from any other machine (Windows does not show them in the Network, Linux does not find them using smbclient).

Is there something to add to the compose file to publish the server to my network? I used network: host as in the example file.

```
version: '3.2'

services:
  samba:
    build: .
    image: ghcr.io/servercontainers/samba
    restart: unless-stopped
    network_mode: host
    hostname: mystorage
    cap_add:
      - CAP_NET_ADMIN
    environment:
      MODEL: 'TimeCapsule'
      AVAHI_NAME: MyStorage

      SAMBA_CONF_LOG_LEVEL: 3
      SAMBA_CONF_SERVER_STRING: MyStorage

      GROUP_familie: 1101

      ACCOUNT_christian: christian
      UID_christian: 1000
      GROUPS_christian: familie

      SAMBA_VOLUME_CONFIG_shared_home: "[Home]; path=/shares/homes/%U; valid users = christian; guest ok = no; read only = no; browseable = yes"
      
      - /etc/avahi/services/:/external/avahi
      
      - /opt/samba/shares/christian:/shares/christian      
```

Best regards
Christian
