### ISSUE TITLE
auth error when use compose list format

### ISSUE THREAD

**Issue by redjumper** [ServerContainers/samba#127]
Hi! Thank you for all the hard work!
When using the list format in compose, I cannot log in to samba. It shows 'The account username or password is wrong‘.
But if using the key-value pair format everything is ok.
The example docker-compose.yml is below

```
services:
  samba:
    image: ghcr.io/servercontainers/samba:latest
    container_name: samba
    mem_limit: 512m
    ports:
      - "445:445"
    networks:
      bridge:
    restart: unless-stopped
    environment:
      - WSDD2_DISABLE=1
      - AVAHI_DISABLE=1
      - ACCOUNT_foo="foo:1000:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:8846F7EAEE8FB117AD06BDD830B7586C:[U          ]:LCT-5FE1F7DF:"
      - UID_foo=1000
      - GROUPS_foo=foo
      - SAMBA_VOLUME_CONFIG_fooonly=[share]; path=/shares; valid users = foo; guest ok = no; read only = no; browseable = yes
    volumes:
      - ./shares:/shares

networks:
  bridge:
    driver: bridge
    ipam:
      driver: default
```
BTW, it would be better if timezone is supported.

**Comment by MarvAmBass** [comment]
thanks for the issue,

interessting - I don't get why this yaml mode breaks the configuration - it shouldn't be much different to the key value way.

timezone is already supported, just mount /etc/timezone into the container and it uses the host timezone.
I'm not sure if I should install `tzdata` so a `TZ=Europe/Berlin` timezone setting would work, it would add around 11MB to the container...

**Comment by MarvAmBass** [comment]
I've added `tzdata` package, you should now be able to set the timezone using the `TZ` env variable.

**Comment by redjumper** [comment]
> I've added `tzdata` package, you should now be able to set the timezone using the `TZ` env variable.

Thanks, it's great that we can now change the timezone via environment variables.


> interessting - I don't get why this yaml mode breaks the configuration - it shouldn't be much different to the key value way.

I believe it's related to quotation marks. 
If we add quotation marks like this
`- SAMBA_VOLUME_CONFIG_fooonly="[share]; path=/shares; valid users = foo; guest ok = no; read only = no; browseable = yes"`
The generated configuration would also include quotation marks, which is not expected.
Quotation marks can be omitted in SAMBA_VOLUME_CONFIG_fooonly, but they cannot be omitted in ACCOUNT_foo.

**Comment by MarvAmBass** [comment]
thanks for investigating this issue further, I wasn't sure what the problem was without fully testing it.

I have to think about a nice way to get rid of those leading and trailing `"`... I'll think about it

**Comment by solipsist01** [comment]
You can solve it like this:

```
services:
  samba:
    image: ghcr.io/servercontainers/samba:latest
    container_name: samba
    mem_limit: 512m
    ports:
      - "445:445"
    restart: unless-stopped
    environment:
      - WSDD2_DISABLE=1
      - AVAHI_DISABLE=1
      - "ACCOUNT_foo=foo:1000:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:8846F7EAEE8FB117AD06BDD830B7586C:[U          ]:LCT-5FE1F7DF:"
      - UID_foo=1000
      - GROUPS_foo=foo
      - "SAMBA_VOLUME_CONFIG_fooonly=[share]; path=/shares; valid users = foo; guest ok = no; read only = no; browseable = yes"
```

**Comment by MarvAmBass** [comment]
thank you @solipsist01 - thanks for figuring this out and sharing this with us

**Comment by vwkd** [comment]
I too have this issue. Trying to connect from Finder on macOS 14.5 indicates username and password are incorrect, even though they are correct. It doesn't show a specific error message and only wiggles the window, but the server address is correct since otherwise it shows an error popup.

I'm running the `smbd-only-latest` container with podman 5.0.3 on Fedora 40 on a custom port 9876 since [rootless podman](https://github.com/containers/podman/blob/009a2441ded538ecdbd96dc2851576adfaf8e28f/rootless.md) can't bind to ports below 1024. Here's the full `docker-compose.yml`

```yml
version: "3"

services:
  samba:
    image: ghcr.io/servercontainers/samba:smbd-only-latest
    environment:
      - ACCOUNT_foo=bar
      - "SAMBA_GLOBAL_STANZA=server signing = mandatory; server min protocol = SMB3; server smb encrypt = required; smb encrypt = required"
      - "SAMBA_VOLUME_CONFIG_fooonly=[Foo Share]; path=/shares/foo; valid users = foo; writeable = yes"
    restart: unless-stopped
    volumes:
    - ./:/shares/foo:Z
    ports:
    - "9876:445"
```

Note: `:Z` is needed to workaround a SELinux issue according to [StackOverflow](https://stackoverflow.com/a/66652632/2607891).
