### ISSUE TITLE
Can't connect on my share remotely and not discovarable

### ISSUE THREAD

**Issue by ZPaul-MYinvest** [ServerContainers/samba#129]
Hello, I want to thank you for your amazing work !
I would like some helps to solve my problem. I'm on macos intel.

Here my service :

```yml
samba:
  image: ghcr.io/servercontainers/samba:latest
  restart: always
  cap_add:
    - CAP_NET_ADMIN
  container_name: samba_server
  hostname: myserver
  networks:
    - smb_macvlan
  environment:
    MODEL: 'TimeCapsule'
    SAMBA_CONF_LOG_LEVEL: 3
    GROUP_fam: 1000
    
    ACCOUNT_dev: somepass
    UID_dev: 1001
    GROUPS_dev: fam

    ACCOUNT_admin: somepass2
    UID_admin: 1002
    GROUPS_admin: fam

    SAMBA_VOLUME_CONFIG_a: |
      [A]
       path = /shares/a
       read only = no
       writable = yes
       access based share enum = Yes
       valid users = dev,admin
       browseable = yes

    SAMBA_VOLUME_CONFIG_b: |
      [B]
       path = /shares/b
       read only = no
       writable = yes
       access based share enum = Yes
       valid users = dev
       browseable = yes

    SAMBA_VOLUME_CONFIG_c: |
      [C]
       path = /shares/c
       read only = no
       writable = yes
       access based share enum = Yes
       valid users = dev,admin
       browseable = yes

    SAMBA_VOLUME_CONFIG_d: |
      [D]
       path = /shares/d
       read only = no
       writable = yes
       access based share enum = Yes
       valid users = dev,admin
       browseable = yes

    SAMBA_VOLUME_CONFIG_e: |
      [E]
       path = /shares/e
       read only = no
       writable = yes
       access based share enum = Yes
       valid users = dev
       browseable = yes
  volumes:
    - "./shares:/shares"
    
    
networks:
  smb_macvlan:
    driver: macvlan
    driver_opts:
      parent: eht0
    ipam:
      config:
        - gateway: X.Y.Z.1
          subnet: X.Y.Z.0/24
          
```
        

I can't find my share manually with something like smb://myserver.local and I can't discover it with avahi.
I honestly think it's something dumb but I can't figure it out.  Thank you in advance for your help.
