### ISSUE TITLE
different GID for www-data when use with another debian cointainer

### ISSUE THREAD

**Issue by petrmatula190** [ServerContainers/samba#141]
Please add note about different GID for www-data between alpine and debian. I used this container with another one (based on debian11-slim, create web server with apache2, and my app in php; my php script generate image thumbnails ftom samba shate data)... So I found permission problem with this sharing setup.

[Small explain](https://stackoverflow.com/a/69290889)

My easy fix is replace force group from www-data to xfs and resolve my issues.

```
services:
  # my cointainer
  web:
    links:
        - db
    depends_on:
        - db
    image: myregistry:5000/avst/debian11-php:1.2.3
    container_name: mycointainer-web
    hostname: mycointainer
    restart: always
    healthcheck:
        test: ["CMD", "curl", "-Ss", "http://localhost"]
        interval: 30s
        timeout: 5s
        retries: 5
    networks:
        - default_mycointainer
    ports:
        - 0.0.0.0:80:80
        - 0.0.0.0:9000:9000
        #- 0.0.0.0:9091:9091 #pro debug supervisord lze zapnout web server
    environment:
        DB_HOST: mycointainer-mariadb #musí odpovídat hostname service db
        DB_USER: ${DB_USER} #.env
        DB_PASSWORD: ${DB_PASSWORD} #.env
        CHMOD_CRON_TIME: "30s"
        STUDIO_SUPORTED_VIDEO_FORMATS: "mp4, webm, ogg" #zapnutí
        #STUDIO_SUPORTED_IMAGE_FORMATS: "jpg, jpeg, png, gif"
        #STUDIO_DEFAULT_NEW_GAL_DURATION_PICKER: "00:10"
        #STUDIO_DEFAULT_GALLERY_START_FROM: 1
        #STUDIO_DEFAULT_TRANSITION_ID: 0
        STUDIO_DEFAULT_SHOW_FULLSCREEN: 0
        #STUDIO_DEFAULT_SHOW_TIME: 1
        #STUDIO_DEFAULT_SHOW_LOGO: 1
        #STUDIO_DEFAULT_PLAY_AUDIO: 1
        #STUDIO_DEFAULT_SLIDE_TYPE_VIDEO_PLAY_AUDIO: 1
    volumes:
        - ./data:/var/www/html/data
        - /etc/localtime:/etc/localtime:ro
  
  db:
    image: mariadb:lts #10.11 - LTS 2/2028
    container_name: mycointainer-db
    hostname: mycointainer-mariadb #musí odpovídat env DB_HOST service web
    restart: always
    networks:
        - default_mycointainer
    healthcheck:
        test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
        interval: 10s
        timeout: 5s
        retries: 5
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} #.env
        MARIADB_AUTO_UPGRADE: "yes"
    volumes:
        - ./avst-db-data:/var/lib/mysql #v případě změny oprávnění stačí použít: sudo chown -R $USER:$USER avst-db-data/
        - /etc/localtime:/etc/localtime:ro
  
  phpmyadmin:
    links:
        - db
    depends_on:
        - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: mycointainer-phpmyadmin
    hostname: mycointainer-phpmyadmin
    restart: always
    healthcheck:
        test: ["CMD", "curl", "-Ss", "http://localhost/robots.txt"]
        interval: 10s
        timeout: 5s
        retries: 5
    networks:
        - default_mycointainer
    ports:
        - 0.0.0.0:8080:80
    environment:
        PMA_HOST: db
        UPLOAD_LIMIT: 2G
    volumes:
      - /etc/localtime:/etc/localtime:ro 
          
  samba:
    image: ghcr.io/servercontainers/samba:latest
    container_name: mycointainer-smb
    hostname: mycointainer-smb
    healthcheck:
      test: ["CMD", "docker-healthcheck.sh"]
      interval: 1m
      start_period: 30s
      timeout: 5s
      retries: 5
    restart: always
    cap_add:
      - CAP_NET_ADMIN
    environment:  
      ACCOUNT_data: ${SMB_ACCOUNT_data} #.env
      GROUP_xfs: 33 # replace www-data with xfs
      GROUPS_data: xfs # replace www-data with xfs
      UID_data: 1000 # must be same as UID in ACCOUNT_data
      TZ: Europe/Prague
      WSDD2_DISABLE: 1
      SAMBA_VOLUME_CONFIG_data: |
        [data]
          comment = Data myapp
          path = /shares/data
          valid users = data
          force user = data
          force group = xfs # replace www-data with xfs
          guest ok = no
          read only = no
          browseable = yes
          create mask = 0775
          directory mask = 0700
    
    networks:
        - samba
    ports:
      - 0.0.0.0:137:137
      - 0.0.0.0:139:139/udp
      - 0.0.0.0:445:445
    volumes:
      - ./data:/shares/data
      - /etc/localtime:/etc/localtime:ro 
      
networks:
  default_mycointainer:
    name: mycointainer_network
  samba:
    name: mycointainer_smb
```

Thanks for add note.
