### ISSUE TITLE
Sharing automounted USB with 'include'

### ISSUE THREAD

**Issue by fawzibr** [ServerContainers/samba#144]
I was thinking of using samba as a container but don't know how to do this part or if there is a way to do it.

In my current samba install (smb.conf) I have the following:

```
include = /etc/samba/usb-shares.conf
```

After some UDEV magic when the USB is connected I add the mount share to /etc/samba/usb-shares.conf and call 'smbcontrol smbd reload-config' and it shares the USB. When the USB is removed, it removes the share and reloads the config again.

I was thinking of doing the following:

```
services:
  samba:
    container_name: samba
    image: ghcr.io/servercontainers/samba
    restart: always
    network_mode: host
    cap_add:
      - CAP_NET_ADMIN
    environment:
      SAMBA_CONF_WORKGROUP: WORKGROUP
      SAMBA_CONF_SERVER_STRING: Samba Server (Docker)
      SAMBA_CONF_SERVER_ROLE: standalone server
      SAMBA_CONF_MAP_TO_GUEST: Bad User
      SAMBA_CONF_LOG_LEVEL: 3
      SAMBA_GLOBAL_CONFIG_wins_SPACE_support: yes
      SAMBA_GLOBAL_CONFIG_follow_SPACE_symlinks: yes
      SAMBA_VOLUME_CONFIG_storage: "[storage]; path=/shares/storage/; browseable = yes; writeable = yes; create mask = 0777; directory mask = 0777; guest ok = yes; guest only = yes"

      # this adds the include file to the smb.conf 
      SAMBA_VOLUME_CONFIG_includes: "include /shares/includes/usb-mounts.conf"
    volumes:
      - /etc/avahi/services/:/external/avahi
      - /storage:/shares/storage
      # this volume will contains the include files
      - /includes-dir:/shares/includes
      # this volume is where UDEV would mount the USBs
      - /usb-mount-dir:/shares/usb
```     

I imagine that would work, my only problem would be the reload config part. So is there a way to reload the config, or have a way to reload the config when the include files changes?
