### ISSUE TITLE
Better explanation of SAMBA_VOLUME_CONFIG_xxx usage

### ISSUE THREAD

**Issue by rolandas-valantinas** [ServerContainers/samba#155]
Hello. Can you please explain how `_samba_custom: "[Samba Custom]` part links to anything else? From example it seems that these can be whatever we want and has no impact as long as they are unique. However, this doesn't seem to be the case in my experience.
```
services:
  samba:
    #build: .
    container_name: samba
    image: ghcr.io/servercontainers/samba:smbd-only-latest
    restart: always
    network_mode: host
    environment:
      GROUP_family: 1500

      ACCOUNT_samba: redacted
      UID_alice: 1000
      GROUPS_alice: family

      SAMBA_VOLUME_CONFIG_samba_custom: "[Samba Custom]; path=/shares/samba; valid users = samba; guest ok = no; read only = no; browseable = yes; force group = family"
    volumes:
      #- /etc/avahi/services/:/external/avahi

      # avoid loops when mounting folders to /shares (I'd recommend explicit mapping for each share)
      - /samba/:/shares/samba
```
With above setup I can't map network drive on windows. But if I use below - it works
```
      SAMBA_VOLUME_CONFIG_samba: "[samba]; path=/shares/samba; valid users = samba; guest ok = no; read only = no; browseable = yes; force group = family"
```
The only change is from `_samba_custom: "[Samba Custom]` to `_samba: "[samba]`

I can't run just with this as I need to add more configs and I can't comprehend why changing what seems to be just titles and identifiers breaks functionality. Thank you in advance!
