### ISSUE TITLE
Container Starts, appears in Network Browser, but unable to connect

### ISSUE THREAD

**Issue by psybernoid** [ServerContainers/samba#156]
I'm attempting to run this container in a macvlan. The container appears to start, I can telnet onto port 445 of the specified IP, but I cannot browse to it to view shares.

My compose:
```

services:
  smb-vlan4:
    image: ghcr.io/servercontainers/samba
    container_name: smb-vlan4
    hostname: totem-vlan4
    restart: unless-stopped
    cap_add:
      - CAP_NET_ADMIN
    networks:
      vlan4:
        ipv4_address: 10.0.1.152
    environment:
      AVAHI_NAME: totem-vlan4
      AVAHI_DISABLE: 1
      GROUP_dockerapps: 5001
      ACCOUNT_user: AbC.123!
      UID_user: 5002
      GROUPS_user: dockerapps
      SAMBA_VOLUME_CONFIG_test: |
        [Test]
          path = /shares/test
          read only = no
          guest ok = no
          valid users = user
          browseable = yes   
    volumes:
      - /mnt/default/docker/smb/vlan4:/external/avahi
      - /mnt/default/test:/shares/test

networks:
  vlan4:
    external: true
```

Log output:

```
################################################################################
Welcome to the ghcr.io/servercontainers/samba
################################################################################
You'll find this container sourcecode here:
    https://github.com/ServerContainers/samba
The container repository will be updated regularly.
################################################################################
mkdir: can't create directory '/var/run/samba': File exists
>> CONTAINER: starting initialisation
>> SAMBA CONFIG: no $SAMBA_CONF_LOG_LEVEL set, using '1'
>> SAMBA CONFIG: no $SAMBA_CONF_WORKGROUP set, using 'WORKGROUP'
>> SAMBA CONFIG: no $SAMBA_CONF_SERVER_STRING set, using 'Samba Server'
>> SAMBA CONFIG: no $SAMBA_CONF_MAP_TO_GUEST set, using 'Bad User'
>> GROUP: adding group dockerapps with GID: 5001
>> ACCOUNT: adding account: user with UID: 5002
startsmbfilepwent_internal: file /var/lib/samba/private/smbpasswd did not exist. File successfully created.
startsmbfilepwent: file /var/lib/samba/private/smbpasswd has invalid permissions 0644 should be 0600.
Added user user.
Changing password for user
New password: 
Retype password: 
passwd: password for user changed by root
New SMB password:
Retype new SMB password:
Enabled user user.
>> ACCOUNT: adding account: user to group: dockerapps
  >> AVAHI: zeroconf model: TimeCapsule
>> VOLUME: adding volume: Test (path=/shares/test)
>> ZEROCONF: custom avahi samba.service name: totem-vlan4
>> ZEROCONF: custom avahi avahi-daemon.conf host-name: totem-vlan4
>> ZEROCONF: samba.service file
############################### START ####################################
<?xml version="1.0" standalone='no'?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
 <name replace-wildcards="yes">totem-vlan4</name>
 <service>
   <type>_smb._tcp</type>
   <port>445</port>
 </service>
 <service>
  <type>_device-info._tcp</type>
  <port>0</port>
  <txt-record>model=TimeCapsule</txt-record>
 </service>
</service-group>
################################ END #####################################
>> AVAHI - DISABLED
>> SAMBA: check smb.conf file using 'testparm -s'
############################### START ####################################
Load smb config files from /etc/samba/smb.conf
# Global parameters
[global]
	dns proxy = No
	load printers = No
	log file = /dev/stdout
	map to guest = Bad User
	obey pam restrictions = Yes
	passdb backend = smbpasswd
	printcap name = /dev/null
	security = USER
	server role = standalone server
	server string = Samba Server
	smb1 unix extensions = No
	fruit:aapl = yes
Loaded services file OK.
Weak crypto is allowed by GnuTLS (e.g. NTLM as a compatibility fallback)
Server role: ROLE_STANDALONE
	fruit:model = TimeCapsule
	idmap config * : backend = tdb
	acl allow execute always = Yes
	mangled names = no
	vfs objects = catia fruit streams_xattr
	wide links = Yes
[Test]
	path = /shares/test
	read only = No
	valid users = user
############################### END ####################################
>> SAMBA: print whole smb.conf
############################### START ####################################
[global]
   server role = standalone server
   log file = /dev/stdout
   dns proxy = no 
   # password stuff
   passdb backend = smbpasswd
   obey pam restrictions = yes
   security = user
   printcap name = /dev/null
   load printers = no
   dns proxy = no
   wide links = yes
   follow symlinks = yes
   unix extensions = no
   acl allow execute always = yes
   # MacOS Compatibility options
   vfs objects = catia fruit streams_xattr
   # Special configuration for Apple's Time Machine
   fruit:model = TimeCapsule
   fruit:aapl = yes
   # fix filenames with special chars (should be default)
   mangled names = no
   dos charset = CP850
   unix charset = UTF-8
   # Docker Envs global config options
   log level = 1
   workgroup = WORKGROUP
   server string = Samba Server
   map to guest = Bad User
[Test]
  path = /shares/test
  read only = no
  guest ok = no
  valid users = user
  browseable = yes   
############################### END ####################################
>> CMD: exec docker CMD
runsvdir -P /container/config/runit
+ sleep 6
+ sleep 2
+ sleep 10
+ exec smbd --foreground
[2025/03/12 14:17:31.887569,  0] ../../source3/smbd/server.c:1746(main)
  smbd version 4.20.6 started.
  Copyright Andrew Tridgell and the Samba Team 1992-2024
+ exec nmbd --foreground
+ exec /usr/sbin/wsdd2
cannot read additional dns hostnames from testparm
cannot read netbios aliases from testparm
starting.
```
