### ISSUE TITLE
Soft link directories via allow insecure wide links not as expected

### ISSUE THREAD

**Issue by mixpc** [ServerContainers/samba#160]
Hello,

Running docker on Ubuntu in a Raspberry Pi 5
```
 cat /etc/os-release
PRETTY_NAME="Ubuntu 24.10"
docker --version
Docker version 28.0.2, build 0442a73
```
This is my docker-compose.yml 
```
services:
  samba:
    build: .
    image: ghcr.io/servercontainers/samba
    container_name: samba
    restart: always
    network_mode: host
    cap_add:
      - CAP_NET_ADMIN
    environment:
      MODEL: 'TimeCapsule'
      AVAHI_NAME: StorageServer
      SAMBA_CONF_LOG_LEVEL: 3
      GROUP_family: 1500
      ACCOUNT_myuser: mypwd
      UID_myuser: 1000
      GROUPS_myuser: family
      SAMBA_VOLUME_CONFIG_betashare: "[betashare]; path=/shares/myshare; valid users = myuser; guest ok = no; read only = no; browseable = yes; follow symlinks = yes; wide links = yes; allow insecure wide links = yes"
    volumes:
      - /etc/avahi/services/:/external/avahi
      - /home/myuser:/shares/myshare
```

In my home user path I have a soft link directory as follows:
```
myuser@ubuntu-server-beta:~/docker/samba$ ls -alh /home/myuser/
total 68K
drwxr-x---  8 myuser myuser 4.0K Mar 22 13:44 .
drwxr-xr-x  3 root   root   4.0K Mar 18 13:26 ..
...
lrwxrwxrwx  1 myuser myuser   13 Mar 18 19:47 USBSSD -> /mnt/USBSSD
```

By setting `allow insecure wide links = yes` I would expect that upon accessing the samba share I would see the contents of /home/myuser including the USBSSD soft link folder. However, what I see is / That is
```
/bin
/boot
/cdrom
/dev
/etc
...
```

In the past, when I created shares by installing apt install samba samba-common-bin my config file...
```
sudo nano /etc/samba/smb.conf
[global]
allow insecure wide links=yes
[betahashare]
comment = my samba share
path = /home/myuser
writeable=Yes
create mask=0777
directory mask=0777
public=no
follow symlinks = yes
wide links = yes
```
... the samba share would show /home/myuser plus the USBSSD soft link directory. So that is why I am raising this issue, in spite of the fact that it might not be an issue as such.

Thank you in advance!
