### ISSUE TITLE
Please provide guidance on sharing mounted volumes.

### ISSUE THREAD

**Issue by codefriar** [ServerContainers/samba#39]
Thank you for your work.

I'm working on adopting this image, and my specific use case is to samba share specific directories on the host machine from the docker image.

I've setup a docker-compose file, defined like this:

```yml
networks:
  samba:
    driver: bridge
services:
  samba:
    restart: unless-stopped
    image: servercontainers/samba:{{ samba.version }}
    networks:
      - samba
    volumes:
      # This is the parent folder of all HLOS storage
      - "{{ storage_dir }}:/media"
    ports:
      - 139:139
      - 445:445
    environment:
      - SAMBA_CONF_WORKGROUP={{samba.workgroup}}
      - SAMBA_CONF_SERVER_STRING={{samba.server_string}}
      - SAMBA_CONF_MAP_TO_GUEST={{samba.map_to_guest}}
      - ACCOUNT_{{default_username}}={{default_password}}
      - SAMBA_VOLUME_CONFIG_HomelabOS="[HomelabOS]; path=/media; guest ok = yes; valid users = {{default_username}} read only = no; browseable = true;"
```

It's being deployed to the host via ansible, so the `{{ var }}` bits are variable substition that also happen to mask my user/pass ;)

Unfortunately, while I can authenticate to the machine using CIFS/SMB it never lets me actually connect, and see files. The logs show this:

```
 >> CONTAINER: starting initialisation                                                                                                                                                                                │
│   >> ACCOUNT: adding account: kpoorman                                                                                                                                                                                 │
│   New password: Retype new password: passwd: password updated successfully                                                                                                                                             │
│   New SMB password:                                                                                                                                                                                                    │
│   Retype new SMB password:                                                                                                                                                                                             │
│   Added user kpoorman.                                                                                                                                                                                                 │
│   Enabled user kpoorman.                                                                                                                                                                                               │
│   >> CMD: exec docker CMD                                                                                                                                                                                              │
│   bash -c smbd -FS -d 2 < /dev/null                                                                                                                                                                                    │
│   smbd version 4.9.5-Debian started.                                                                                                                                                                                   │
│   Copyright Andrew Tridgell and the Samba Team 1992-2018                                                                                                                                                               │
│   uid=0 gid=0 euid=0 egid=0                                                                                                                                                                                            │
│   Registered MSG_REQ_POOL_USAGE                                                                                                                                                                                        │
│   Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED                                                                                                                                                                      │
│   added interface eth0 ip=172.28.0.2 bcast=172.28.255.255 netmask=255.255.0.0                                                                                                                                          │
│   INFO: Profiling support unavailable in this build.                                                                                                                                                                   │
│   daemon_ready: STATUS=daemon 'smbd' finished starting up and ready to serve connections                                                                                                                               │
│   Failed to fetch record!                                                                                                                                                                                              │
│   waiting for connections                                                                                                                                                                                              │
│   samba_tevent: EPOLL_CTL_DEL EBADF for fde[0x55e759dd1510] mpx_fde[(nil)] fd[12] - disabling                                                                                                                          │                                                                                                         │
│   check_ntlm_password:  authentication for user [kpoorman] -> [kpoorman] -> [kpoorman] succeeded                                                                                                                       │
│   process_usershare_file: stat of /var/lib/samba/usershares/homelabos failed. No such file or directory                                                                                                                │
│   process_usershare_file: stat of /var/lib/samba/usershares/homelabos failed. No such file or directory                                                                                                                │
│   process_usershare_file: stat of /var/lib/samba/usershares/homelabos failed. Permission denied                                                                                                                        │
│   process_usershare_file: stat of /var/lib/samba/usershares/homelabos failed. Permission denied                                                                                                                        │
│   check_usershare_stat: file /var/lib/samba/usershares/ owned by uid 0 is not a regular file
```

I'm not sure what i need to do to enable this?

**Comment by MarvAmBass** [comment]
Hi there,

thanks for using my container.
I just looked over your infos and it seems like it should work 

I also just tried to start the container (current latest) with my provided docker-compose file - it also works.

for me it's just an issue with the permissions on your share. try to read about samba and permissions and make sure the user you add is able to write on those directory.

after that it should work

**Comment by codefriar** [comment]
Thanks for the quick reply. I'm still slightly confused.

the username created is the same as the host system. In this case kpoorman. Additionally,
the user id's match (host: 1000, container:1000) and the folder shared is mounted as my user. 

I've modified my compose file to more closely match yours - 

```yml
networks:
  samba:
    driver: bridge

services:
  samba:
    restart: unless-stopped
    image: servercontainers/samba:latest
    networks:
      - samba
    volumes:
      # This is the parent folder of all HLOS storage
      - "/mnt/homelabos/media:/shares/kpoorman"
    ports:
      - 139:139
      - 445:445
    environment:
      - SAMBA_CONF_WORKGROUP=WORKGROUP
      - SAMBA_CONF_SERVER_STRING=File Server
      - SAMBA_CONF_MAP_TO_GUEST=Bad User
      - ACCOUNT_kpoorman=notToday
      - SAMBA_VOLUME_CONFIG_HomelabOS="[HomelabOS]; path=/shares/kpoorman; guest ok = yes; valid users = kpoorman read only = no; browseable = true;"
```

However, I still get 

```
samba_1  | check_ntlm_password:  authentication for user [kpoorman] -> [kpoorman] -> [kpoorman] succeeded
samba_1  | process_usershare_file: stat of /var/lib/samba/usershares/homelabos failed. No such file or directory
samba_1  | process_usershare_file: stat of /var/lib/samba/usershares/homelabos failed. No such file or directory
samba_1  | process_usershare_file: stat of /var/lib/samba/usershares/homelabos failed. Permission denied
samba_1  | process_usershare_file: stat of /var/lib/samba/usershares/homelabos failed. Permission denied
samba_1  | check_usershare_stat: file /var/lib/samba/usershares/ owned by uid 0 is not a regular file
``` 

But /var/lib/samba/usershares isn't mentioned anywhere in my config. (or yours) please advise
