### ISSUE TITLE
Avahi service-group tag isn't closed with multiple txt-records

### ISSUE THREAD

**Issue by openfirmware** [ServerContainers/samba#40]
Hello! I found your project as one of the easiest to adapt as a TimeMachine Samba container.

I was able to access Samba with a direct connection from MacOS, but it would not appear in auto-discovery. In the startup log, I noticed `</service-group>` was missing at the end of `samba.service`:

```
>> ZEROCONF: samba.service file                                                                                                                           
############################### START ####################################            
<?xml version="1.0" standalone='no'?>                                                                                                                     
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">                                          
<service-group>                                                                                                                                           
 <name replace-wildcards="yes">My TimeCapsule</name>                                
 <service>                                                                            
   <type>_smb._tcp</type>                                                                                                                                
   <port>445</port>                                                                        
 </service>                                                                                                                                               
                                                                                    
 <service>                                                                                                                                                
  <type>_device-info._tcp</type>                                                                                                                          
  <port>0</port>                                                                      
  <txt-record>model=TimeCapsule</txt-record>                                                                                                             
 </service>                                                                                                                                              
                                                                                                                                                          
 <service>                                                                            
  <type>_adisk._tcp</type>                                                                                                                          
  <txt-record>sys=waMa=0,adVF=0x100</txt-record>                                      
  <txt-record>dk0=adVN=TimeCapsule A,adVF=0x82</txt-record>                                                                                  
  <txt-record>dk1=adVN=TimeCapsule B,adVF=0x82</txt-record>             
  <txt-record>dk2=adVN=TimeCapsule C,adVF=0x82</txt-record>                                                                             
 </service>                                                                                                                                         
################################ END #####################################
```

I cloned the repo and modified `scripts/entrypoint.sh` and modified line 123 to not insert `</service-group>` at the end of the `samba.service` file. Instead, I added it after the if-block for dk txt-records, on line 129 or so:

```bash
        if ! grep '<txt-record>dk' /etc/avahi/services/samba.service 2> /dev/null >/dev/null;
        then
          # for first time add complete service
          echo '
 <service>
  <type>_adisk._tcp</type>
  <txt-record>sys=waMa=0,adVF=0x100</txt-record>
  <txt-record>dk'"$NUMBER"'=adVN='"$VOL_NAME"',adVF=0x82</txt-record>
 </service>' >> /etc/avahi/services/samba.service
        else
          # from the second one only append new txt-record
          REPLACE_ME=$(grep '<txt-record>dk' /etc/avahi/services/samba.service | tail -n 1)
          sed -i 's;'"$REPLACE_ME"';'"$REPLACE_ME"'\n  <txt-record>dk'"$NUMBER"'=adVN='"$VOL_NAME"',adVF=0x82</txt-record>;g' /etc/avahi/services/samba.service
        fi
        echo '
</service-group>' >> /etc/avahi/services/samba.service
    fi
```

I modified my local `docker-compose.yml` to use this new context, and it works perfectly now.

**Comment by MarvAmBass** [comment]
I, thanks for using my container and writing this bug record.

Really strange, could you please provide your `docker-compose.yml` (make sure to delete passwords and personal data)?

If you look on how this is written, it will only add the whole service if no '<txt-record>dk'  is found. after that, every other timemachine, will be integrated inside this `service`-tag using a `sed` replacement.
I don't really understand why the `</service-group>` was missing in the first place...


ohh okay I found it - https://github.com/ServerContainers/samba/blob/master/scripts/entrypoint.sh#L85 deletes `</service-group>`. so this should only be run the first time a timemachine volume is recognized. I'll create a fix and push it asap.

Thanks for reporting this bug! 👍  Have fun with the container!

P.S. `I found your project as one of the easiest to adapt as a TimeMachine Samba container.` thanks, but didn't it work out of the box - did you need other improvements for it to work?

**Comment by MarvAmBass** [comment]
fixed

**Comment by openfirmware** [comment]
Here is the `docker-compose.yml`.

I have a few MacBooks I was upgrading/moving and wanted to try this Dockerfile as a way of giving each their own set of user/pass and isolated shares.

I am using `macvlan` as I wanted to test it out alongside the Samba/Avahi already running on the Docker host, and having the container act as a new network device seems to work. I haven't tested ipv6 as I haven't set it up on my home network yet, maybe one day.

The shares are on a ZFS pool, each share being it's own ZFS filesystem with its own quota set. This quota is then seen by the container as the amount of space available and is passed along to Time Machine clients.

I don't know if the `vfs objects = fruit streams_xattr;` on each volume config is necessary, I added that while I was trying to get it working before I noticed the Avahi config bug. I copied that stanza from the Time Machine Samba setup I have on the Docker host for my older Mac computer.

```yaml
# Tested with Docker Engine 19.03.14
# Version 2 is used, as I found it easier to understand the documentation without the Docker Swarm options in Version 3
version: '2.4'

services:
  samba:
    image: servercontainers/samba
    
    networks:
      smb_macvlan:
        ipv4_address: 10.0.1.55

    restart: unless-stopped

    environment:
      AVAHI_NAME: 'My TimeCapsule'
      MODEL: 'TimeCapsule'

      ACCOUNT_device_A: "deviceAPass"
      ACCOUNT_device_B: "deviceBPass"
      ACCOUNT_device_C: "deviceCPass"

      SAMBA_VOLUME_CONFIG_device_A: "[TimeCapsule Device A]; path=/shares/device_a; valid users = device_A; guest ok = no; read only = no; browseable = no; fruit:time machine = yes; vfs objects = fruit streams_xattr;"
      SAMBA_VOLUME_CONFIG_device_B: "[TimeCapsule Device B]; path=/shares/device_b; valid users = device_B; guest ok = no; read only = no; browseable = no; fruit:time machine = yes; vfs objects = fruit streams_xattr;"
      SAMBA_VOLUME_CONFIG_device_C: "[TimeCapsule Device C]; path=/shares/device_c; valid users = device_C; guest ok = no; read only = no; browseable = no; fruit:time machine = yes; vfs objects = fruit streams_xattr;"

    volumes:
      - "/myzpool/backup/device_a:/shares/device_a"
      - "/myzpool/backup/device_b:/shares/device_b"
      - "/myzpool/backup/device_c:/shares/device_c"

networks:
  smb_macvlan:
    driver: macvlan
    enable_ipv6: false
    driver_opts:
      parent: br0
    ipam:
      driver: default
      config:
        - gateway: 10.0.1.1
          subnet: 10.0.1.0/24
```

Hope this helps anyone trying the same. 👍
