### ISSUE TITLE
Issue with multiple home directories

### ISSUE THREAD

**Issue by eyeruleall** [ServerContainers/samba#41]
Hey, I've been using this container for years, and recently added a second user and came across a bug.

With one user configured in the docker-compose file, if I mount my /home dir and add:
`SAMBA_VOLUME_CONFIG_homes: "[homes]; writable = yes; browseable = no;"`
to the docker-compose file, all works fine.

When I add a second ACCOUNT_username to the docker-compose file, I lose write access to the shared home folder.

```
...
    environment:
      ACCOUNT_user1: user1pass
      ACCOUNT_user2: user2pass
      SAMBA_VOLUME_CONFIG_homes: "[homes]; writable = yes; browseable = no;"
    volumes:
      - /home:/home
```

Is there a preferred way of sharing home folders?

**Comment by MarvAmBass** [comment]
Hi there, it seems to me, that this is an issue regarding the `uid` missmatch

- when adding a new user to this container using `ACCOUNT_...` a new useradd command will be run inside the container and the user gets a new userid. which might be the same as your user, or might be different.

can you clearify, that the uids of your accounts and the ones on the samba server mismatch?

I was thinking about a solution for this scenario, where you specify the `UID_...` for each user - so it will have the same as your client system

**Comment by MarvAmBass** [comment]
I just added a fix which might help

```
    environment:
      ACCOUNT_user1: user1pass
      ACCOUNT_user2: user2pass
      UID_user1: 2000
      UID_user2: 2001
      SAMBA_VOLUME_CONFIG_homes: "[homes]; writable = yes; browseable = no;"
    volumes:
      - /home:/home

```

please replace the UID `2000` or `2001` with the correct user ids your users will have

kind regards :)
