### ISSUE TITLE
[Feature request] Customize user gid through an environment variable

### ISSUE THREAD

**Issue by shadowking001** [ServerContainers/samba#45]
Hello ! Me again, sorry to disturb you ! 😄 

I got a request for you. Actually, If I try to write on a share with a defined user, e.g. media, the file will belong to media/media (for an uid=1035, so 1035/1035). This is perfectly fine on a classic Linux distros, but NASes and their custom Linux implementations are often locking gid group values to a certain extent.

For instance, Synology are using gid=100 for basic users, and 65000+ for user-defined groups.
To ensure there aren't any denied permission, being able to choose the GID of our user would be awesome, have a look on the following screenshot, if I could set GID_media=100 (gid of "users" group), it would be flawless :

![gid_samba](https://user-images.githubusercontent.com/43928955/131320106-476c39aa-a717-46be-be07-b0792585e272.PNG)

**Comment by MarvAmBass** [comment]
so you're talking about the main user group id?

**Comment by shadowking001** [comment]
About the main gid right.
I can conduct some tests to see if it effectively leads to bugs about permissions.
But I'm afraid it could.

**Comment by MarvAmBass** [comment]
I currently plan if we make it possible to set a list of groups and new groups+ids with the first group being the main group... I guess this should work for all possible use cases 🤔

**Comment by MarvAmBass** [comment]
done and pushed, you can now create groups using environment variables and also specify a list of groups added to each account - this should solve your problem

**Comment by shadowking001** [comment]
Thanks for your effort, here is my new compose file :

```
version: '2.1'
services:

   samba-server:
      image: servercontainers/samba
      container_name: samba-server
      hostname: samba-nt1
      networks:
         mac0:
            ipv4_address: 192.168.100.145
      environment:

         ## lawrence user ##
         - ACCOUNT_lawrence=lawrence-smb
         - UID_lawrence=1027
         - GROUPS_lawrence=users
         
         ## media user ##
         - ACCOUNT_media=media-smb
         - UID_media=1035
         - GROUPS_media=users
         
         ## Groups definition ##
         - GROUP_users=100
         
         ## Directives and shares config ##
         - SAMBA_GLOBAL_CONFIG_server_SPACE_min_SPACE_protocol=NT1
         - SAMBA_GLOBAL_CONFIG_ntlm_SPACE_auth=ntlmv1-permitted
         - SAMBA_CONF_MAP_TO_GUEST=Never
         - SAMBA_VOLUME_CONFIG_music=[Musique]; path=/shares/music; guest ok = no; read only = no; browseable = yes; valid users = lawrence, media
         
      volumes:
         - /volume1/music/bibliotheque:/shares/music
         - /volume1/docker/samba/conf-server:/etc/samba
      restart: unless-stopped

networks:

   mac0:
      external: true
```

For exemple, I am checking whose group media is belonging to :

`docker exec -it samba-server id media`
`uid=1035(media) gid=1035(media) groups=1035(media),100(users)`

If I upload any file to the volume, it ends up belonging to media/media, I'd like it to be media/users instead.

I'm pretty sure what I get is the expected behaviour, if so I'll probaby get over it (asking people to chown regularly, but not a smart solution), but asking you just to be sure I'm not missing something obvious.
