### ISSUE TITLE
Invalid option -FS: unknown option

### ISSUE THREAD

**Issue by a1ad** [ServerContainers/samba#51]
```
When starting the conatiner iv got this error in a loop:

>> CMD: exec docker CMD
samba-samba-1  | runsvdir -P /container/config/runit
samba-samba-1  | cannot read additional dns hostnames from testparm
samba-samba-1  | cannot read netbios aliases from testparm
samba-samba-1  | starting.
samba-samba-1  | 
samba-samba-1  | Invalid option -FS: unknown option
samba-samba-1  | 
samba-samba-1  | Usage: smbd [-?bDiFV] [-?|--help] [--usage] [-b|--build-options]
samba-samba-1  |         [-p|--port=STRING] [-P|--profiling-level=PROFILE_LEVEL]
samba-samba-1  |         [-d|--debuglevel=DEBUGLEVEL] [--debug-stdout]
samba-samba-1  |         [-s|--configfile=CONFIGFILE] [--option=name=value]
samba-samba-1  |         [-l|--log-basename=LOGFILEBASE] [--leak-report] [--leak-report-full]
samba-samba-1  |         [-D|--daemon] [-i|--interactive] [-F|--foreground]
samba-samba-1  |         [--no-process-group] [-V|--version]
samba-samba-1  | 
samba-samba-1  | Invalid option -FS: unknown option

```

**Comment by MarvAmBass** [comment]
Hi there, can you pull again? this image was broken a few days ago for around 30 minutes - seems like you pulled that broken version

**Comment by MarvAmBass** [comment]
tried it with a fresh pull and it seems to work nicly

**Comment by a1ad** [comment]
sorry, same problem

**Comment by a1ad** [comment]
Here is my config file:

```
version: '3'
 
services:
  samba:
    build: .
    image: servercontainers/samba
    hostname: NAS
    cap_add:
      - CAP_NET_ADMIN
      
    environment:
      MODEL: 'TimeCapsule'
      AVAHI_NAME: StorageServer
      SAMBA_CONF_WORKGROUP: protech      
      
      ACCOUNT_jeroen: password
      UID_jeroen: 1000
      
      ACCOUNT_nathalie: password
      UID_nathalie: 1001
      
      GROUP_Backups: 1001
      GROUP_Downloads: 1002
      GROUP_Games: 1003
      GROUP_Media: 1005
      GROUP_Music: 1006
      GROUP_TMP: 1007
      GROUP_Pictures: 1008
      GROUP_Personal: 1011
      GROUP_Dump: 1012
      GROUP_Ebooks: 1013
      GROUP_Docs: 1015
      GROUP_Sport: 1016
      GROUP_Movies: 1014
      GROUP_veeam: 1021
      GROUP_Software: 1009
      GROUPS_jeroen: Backups,Downloads,Games,nathalie,Media,Music,TMP,Pictures,Dump,Ebooks,Docs,Sport,Movies,veeam,Software
      GROUPS_nathalie: Media,Music,Pictures,Personal,Dump,Software     
      
      SAMBA_VOLUME_CONFIG_Downloads: "[Downloads]; path=/shares/Downloads; valid users = @Downloads; force group = Downloads; invalid users = braxxess martijn nico nathalie"
      SAMBA_VOLUME_CONFIG_Games: "[Games]; path=/shares/Games; valid users = @Games; force group = Games; invalid users = braxxess martijn nico"
      SAMBA_VOLUME_CONFIG_Software: "[Software]; path=/shares/Software; valid users = @Software; force group = Software; invalid users = braxxess nico; read list = martijn nathalie"
      SAMBA_VOLUME_CONFIG_Media: "[Media]; path=/shares/Media; valid users = @Media; force group = Media; invalid users = braxxess martijn nico; read list = nathalie"
      SAMBA_VOLUME_CONFIG_Personal: "[Personal]; path=/shares/Personal;         vfs objects = shadow_copy2; invalid users = braxxess martijn nico"
      SAMBA_VOLUME_CONFIG_Dump: "[Dump]; path=/shares/Dump; valid users = @Dump; force group = Downloads"
      SAMBA_VOLUME_CONFIG_veeam: "[veeam]; path=/shares/veeam; force group = veeam; force user = root; invalid users = braxxess martijn nico"
      SAMBA_VOLUME_CONFIG_TMP: "[TMP]; path=/shares/TMP; force group = TMP; force user = root; invalid users = braxxess martijn nico nathalie"
    

    volumes:
#      - /etc/avahi/services/:/external/avahi
      
      - /wdpool/NAS/Downloads:/shares/Downloads
      - /bds/NAS/Games:/shares/Games
      - /bds/NAS/Software:/shares/Software
      - /bds/NAS/Media:/shares/Media
      - /bds/NAS/Personal:/shares/Personal
      - /bds/NAS/Dump:/shares/Dump
      - /bds/NAS/veeam:/shares/veeam
      - /bds/NAS/TMP:/shares/TMP
      #- /bds/NAS/Backups/Timemachines:/shares/Timemachine
      
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
      
    restart: unless-stopped
```
