### ISSUE TITLE
vsf support (recycle bin)

### ISSUE THREAD

**Issue by vbeskrovny** [ServerContainers/samba#58]
Hi, thank you for the container.

Does it support vfs? (for the recycle bin).

**Comment by vbeskrovny** [comment]
closed

**Comment by MarvAmBass** [comment]
It does and it works with the latest release - was broken in the previous one for unknown reasons - some kind of broken alpine apk I'd guess

**Comment by vbeskrovny** [comment]
Alright. Thank you!

Feb 12, 2022 09:25:17 Marvin ***@***.***>:

**Comment by angussidney** [comment]
For anyone who is also wondering how to enable file recycling, you may want to add the following smb.conf lines using environment variables. (Note this is based on the configuration options set in the [dperson/samba](https://github.com/dperson/samba/blob/master/Dockerfile) container)
```yml
    environment:
        # vfs objects = catia fruit recycle streams_xattr
        SAMBA_GLOBAL_CONFIG_vfs_SPACE_objects: "catia fruit recycle streams_xattr"
        # recycle:keeptree = yes
        SAMBA_GLOBAL_CONFIG_recycle_COLON_keeptree: "yes"
        # recycle:maxsize = 0
        SAMBA_GLOBAL_CONFIG_recycle_COLON_maxsize: "0"
        # recycle:repository = .deleted
        SAMBA_GLOBAL_CONFIG_recycle_COLON_repository: ".deleted"
        # recycle:versions = yes
        SAMBA_GLOBAL_CONFIG_recycle_COLON_versions: "yes"
```
