### ISSUE TITLE
Shares are readonly

### ISSUE THREAD

**Issue by a1ad** [ServerContainers/samba#59]
All my shares are readonly. What am I doing wrong here?

config:
```
version: '3'
 
services:
  samba:
    build: .
    image: servercontainers/samba
    container_name: samba
    #network_mode: host
    hostname: ${SMB_SERVER_NAME}
      
    environment:
      MODEL: 'TimeCapsule'
      AVAHI_NAME: ${SMB_SERVER_NAME}
      SAMBA_CONF_WORKGROUP: protech    
      SAMBA_CONF_LOG_LEVEL: 3

      # uncomment to disable optional services
      #WSDD2_DISABLE: 1
      #AVAHI_DISABLE: 1
      
      ACCOUNT_jeroen: ${SMB_PWD_JEROEN}
      UID_jeroen: 1000
      
      ACCOUNT_nathalie: ${SMB_PWD_NATHALIE}
      UID_nathalie: 1020
      
      GROUP_Backups: 1001
      GROUP_Downloads: 1002
      GROUP_Games: 1003
      GROUP_Nathalie: 1004
      GROUP_Media: 1005
      GROUP_Music: 1006
      GROUP_TMP: 1007
      GROUP_Pictures: 1008
      GROUP_Software: 1009
      GROUP_Jeroen: 1010
      GROUP_Personal: 1011
      GROUP_Dump: 1012
      GROUP_Ebooks: 1013
      GROUP_Movies: 1014
      GROUP_Docs: 1015
      GROUP_Sport: 1016
      GROUP_veeam: 1021
      GROUPS_jeroen: Backups,Downloads,Games,Nathalie,Media,Music,TMP,Pictures,Dump,Ebooks,Docs,Sport,Movies,veeam,Software,Jeroen,Personal
      GROUPS_nathalie: Media,Music,Pictures,Personal,Dump,Software,Nathalie
      
      #Download share
      SAMBA_VOLUME_CONFIG_Downloads: "[Downloads]; path=/shares/Downloads; valid users = @Downloads; force group = Downloads; invalid users = nathalie"
      #Software share
      SAMBA_VOLUME_CONFIG_Software: "[Software]; path=/shares/Software; valid users = @Software; force group = Software; read list = nathalie"
      #Media share
      SAMBA_VOLUME_CONFIG_Media: "[Media]; path=/shares/Media; valid users = @Media; force group = Media; read list = nathalie"
      #Personal share
      SAMBA_VOLUME_CONFIG_Personal: "[Personal]; path=/shares/Personal"
      #Dump share
      SAMBA_VOLUME_CONFIG_Dump: "[Dump]; path=/shares/Dump; valid users = @Dump; force group = Downloads"

    volumes:      
      - ${NAS_FOLDER}/Downloads:/shares/Downloads
      - ${NAS_FOLDER}/Software:/shares/Software
      - ${NAS_FOLDER}/Media:/shares/Media
      - ${NAS_FOLDER}/Personal:/shares/Personal
      - ${NAS_FOLDER}/Dump:/shares/Dump
      
    ports:
      - ${Host_LAN_IP}:137:137/udp
      - ${Host_LAN_IP}:138:138/udp
      - ${Host_LAN_IP}:139:139/tcp
      - ${Host_LAN_IP}:445:445/tcp
      
    restart: unless-stopped

```

Filesystem:
```
total 20
drwxrwx--- 2 root   1002 4096 Dec  4  2016 Downloads
drwxrwx--- 7 jeroen 1012 4096 Feb 19 20:26 Dump
drwxrwx--- 9 jeroen 1005 4096 Feb 20 19:19 Media
drwxrwx--- 5 root   1011 4096 Feb 19 19:46 Personal
drwxrwx--- 8 jeroen 1009 4096 Nov 18 16:15 Software
```

Container logs:
```
Attaching to samba
samba  | ################################################################################
samba  | 
samba  | Welcome to the servercontainers/samba
samba  | 
samba  | ################################################################################
samba  | 
samba  | >> CONTAINER: already initialized - direct start of samba
samba  | >> CMD: exec docker CMD
samba  | runsvdir -P /container/config/runit
samba  | Process 326 died: No such process; trying to remove PID file. (/run/avahi-daemon//pid)
samba  | Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
samba  | Successfully dropped root privileges.
samba  | avahi-daemon 0.8 starting up.
samba  | WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
samba  | Successfully called chroot().
samba  | Successfully dropped remaining capabilities.
samba  | Loading service file /services/samba.service.
samba  | Joining mDNS multicast group on interface eth0.IPv4 with address 172.16.9.2.
samba  | New relevant interface eth0.IPv4 for mDNS.
samba  | Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
samba  | New relevant interface lo.IPv4 for mDNS.
samba  | Network interface enumeration completed.
samba  | Registering new address record for 172.16.9.2 on eth0.IPv4.
samba  | Registering new address record for 127.0.0.1 on lo.IPv4.
samba  | cannot read additional dns hostnames from testparm
samba  | cannot read netbios aliases from testparm
samba  | starting.
samba  | open_ep: SO_RCVBUFFORCE: Operation not permitted
samba  | Server startup complete. Host name is NASje.local. Local service cookie is 4067034504.
samba  | Service "NASje" (/services/samba.service) successfully established.

```

Here I am trying to remove a file in the Dump folder as samba user: jeroen

<img width="480" alt="image" src="https://user-images.githubusercontent.com/29516835/155883377-f65cd952-5a29-472b-b3e3-7906ffb2d26b.png">
