### ISSUE TITLE
Can't access the share after adding root account

### ISSUE THREAD

**Issue by weeix** [ServerContainers/samba#62]
Hi,

I'm using Docker in [rootless mode][1], which map uid 0 in the container to my uid on the host. However, after adding `ACCOUNT_root`, `UID_root`, and `GROUPS_root`, the share (Backups) can't be accessed anymore (not even by the non-root account). The public share can still be used though.

`docker-compose.yml`:

```
services:
  samba:
    container_name: samba
    hostname: ${SMB_SERVER_NAME}
    image: servercontainers/samba:a3.15.4-s4.15.5-r0
    cap_add:
     - CAP_NET_ADMIN
    env_file:
      - .env
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - ./backups:/shares/backups
      - ./public:/shares/public
    restart: always
```

`.env`:

```
TZ=Asia/Bangkok
SMB_SERVER_NAME=orangepi
GROUP_family=1500
ACCOUNT_alice=alipass
UID_alice=1000
GROUPS_alice=family
ACCOUNT_root=rootpass
UID_root=0
GROUPS_root=family
SAMBA_CONF_LOG_LEVEL=3
SAMBA_VOLUME_CONFIG_Public=[Public]; path=/shares/public; guest ok = yes; read only = no; browseable = yes
SAMBA_VOLUME_CONFIG_Backups=[Backups]; path=/shares/backups; valid users = alice, root; guest ok = no; read only = no; browseable = yes; force group = family
```

`ls -la` on the host:

```
drwxrwxrwx 2 myuser myuser 4096 Apr 13 12:20 backups
-rw-r--r-- 1 myuser myuser  445 Apr 13 12:03 docker-compose.yml
-rw-r--r-- 1 myuser myuser  471 Apr 13 12:30 .env
drwxrwxrwx 2 myuser myuser 4096 Apr 13 12:12 public
```

`ls -la /shares/` in the container:

```
drwxr-xr-x    4 root     root          4096 Apr 13 05:04 .
drwxr-xr-x    1 root     root          4096 Apr 13 05:30 ..
drwxrwxrwx    2 root     root          4096 Apr 13 05:20 backups
drwxrwxrwx    2 root     root          4096 Apr 13 05:12 public
```

Logs: https://gist.github.com/weeix/e7ee6bd6521995bd9ded68b833b9d86c

Sceenshot:

![image](https://user-images.githubusercontent.com/6592791/163108037-7d30ea59-2d3d-42b9-9ca8-173a804e6645.png)

Server Env:

- Armbian 11 (bullseye)
- Docker 20.10.14 (linux/arm64)
- Docker Compose 2.4.1
- servercontainers/samba:a3.15.4-s4.15.5-r0

Client Env:

- Windows 11 Home 21H2

[1]: https://docs.docker.com/engine/security/rootless/
