### ISSUE TITLE
Samba share is not announced

### ISSUE THREAD

**Issue by bpoetzschke** [ServerContainers/samba#66]
Hi there,

I setup the docker image based on the docker compose example. However, I have not been able to see the samba share being announced on the network. I'm running the image on a raspberry pi. On my mac I have to manually connect to the server to be able to access the share.

Here is my configuration:
```yaml
   samba:
    image: servercontainers/samba
    restart: always
    network_mode: host
    environment:
      MODEL: 'MacPro7,1@ECOLOR=226,226,224'
      AVAHI_NAME: StorageServer
      WSDD2_DISABLE: 1
      SAMBA_CONF_LOG_LEVEL: 3
      GROUP_family: 1500
      ACCOUNT_bjoern: "bjoern:redacted"
      UID_bjoern: 1000
      GROUPS_bjoern: family

      SAMBA_VOLUME_CONFIG_shared_home: "[NetShare]; path=/shares/samba_data; valid users = bjoern; guest ok = no; read only = no; browseable = yes"
      SAMBA_VOLUME_CONFIG_timemachine: "[TimeMachine]; path=/shares/timemachine/%U; valid users = bjoern; guest ok = no; read only = no; browseable = yes; fruit:time machine = yes; fruit:time machine max size = 500G"
    volumes:
      - /etc/avahi/services/:/external/avahi
      - /4tb_hdd/samba_data:/shares/samba_data
      - /4tb_hdd/timemachine_data:/shares/timemachine_data
```
