### ISSUE TITLE
Remove VOLUME declaration from Dockerfile

### ISSUE THREAD

**Issue by ndm13** [ServerContainers/samba#68]
I'm currently using `servercontainers/samba:smbd-wsdd2-latest` in this docker-compose stack deployed through Portainer:

```yml
version: '2.0'

services:
  samba:
    image: servercontainers/samba:smbd-wsdd2-latest
    container_name: samba
    hostname: my-hostname
    cap_add:
      - CAP_NET_ADMIN
    environment:
      ACCOUNT_samba: $PASSWORD
      UID_samba: 1000
      SAMBA_VOLUME_CONFIG_out: "[My Share];path=shares/out;valid users=samba;guest ok=no;read only=no;browsable=yes"
    restart: unless-stopped
    volumes:
      - /scratch/folder1:/shares/out/folder1:rw
      - /scratch/folder2/output:/shares/out/folder2:rw
      - /scratch/folder3/output:/shares/out/folder3:rw
      - /scratch/folder4:/shares/out/folder4:rw
      - /scratch/folder5:/shares/out/folder5:rw
networks:
  default:
    name: peer
    external: true
```

This setup works great (`peer` is an ipvlan peered to `host`), but as I was cleaning up my instance I noticed a rogue volume associated with this container mounted at `/shares`.  This is coming from a [`VOLUME ["shares"]` in the Dockerfile](https://github.com/ServerContainers/samba/blob/0777b38012e3b6e8bb00720634fc35473d860f49/Dockerfile#L244).  In my setup, this volume is meaningless, because I'm mounting into subdirectories of that folder.  And I can't create a single combined volume and mount it at `/shares` without setting up symlinks on the host, which I'd prefer to not do.

Would removing this break any expected behavior?  My understanding is that this would be mounted manually anyway, either directly or at a subfolder level.  The only case where I can see this breaking is someone using this as a place to create empty shares and fill them, but having that data stored in an anonymous volume seems dangerous.

**Comment by MarvAmBass** [comment]
Hi there,

I'm somehow with you, but depending on your environment it might be impossible/blocked to mount directories into this container if there is now VOLUME specified. RedHat OpenShift supports those policies, maybe vanilla k8s too.

That's the reason I can't remove the `shares` Volume.

I know, that for normal Docker Users this is usually not an issue.

**Comment by uwekoenig** [comment]
Binding the shares to a non-standard path like `/myshares/folder1` and binding the standard `/shares` directory to a temporary filesystem by adding 
```
services:
  samba:
    ...
    tmpfs:
      - /shares
```
 solved the problem for me.
