### ISSUE TITLE
Latest tag fails to init user

### ISSUE THREAD

**Issue by gravufo** [ServerContainers/samba#73]
The latest version of the image seems to fail on startup when setting up the users.

Here is a sample compose file:
```yaml
services:
  samba:
    image: servercontainers/samba
    cap_add:
      - CAP_NET_ADMIN
    network_mode: host
    restart: unless-stopped
    environment:
      SAMBA_CONF_WORKGROUP: HOME
      ACCOUNT_admin: password
      UID_admin: 1000
      GROUPS_admin: admin
      GROUP_admin: 1000
      SAMBA_VOLUME_CONFIG_backup: "[Backup]; path=/shares/backup; valid users = admin; guest ok = no; read only = no; browseable = yes"
    volumes:
      - /mnt/backup:/shares/backup
```

Here is the beginning of the log when starting the container for the first time:
```
samba-samba-1  | ################################################################################
samba-samba-1  |
samba-samba-1  | Welcome to the servercontainers/samba
samba-samba-1  |
samba-samba-1  | ################################################################################
samba-samba-1  |
samba-samba-1  | >> CONTAINER: starting initialisation
samba-samba-1  | >> SAMBA CONFIG: no $SAMBA_CONF_LOG_LEVEL set, using '1'
samba-samba-1  | >> SAMBA CONFIG: no $SAMBA_CONF_SERVER_STRING set, using 'Samba Server'
samba-samba-1  | >> SAMBA CONFIG: no $SAMBA_CONF_MAP_TO_GUEST set, using 'Bad User'
samba-samba-1  | >> GROUP: adding group admin with GID: 1000
samba-samba-1  | >> ACCOUNT: adding account: admin with UID: 1000
samba-samba-1  | adduser: uid '1000' in use
samba-samba-1  | startsmbfilepwent_internal: file /var/lib/samba/private/smbpasswd did not exist. File successfully created.
samba-samba-1  | Failed to add entry for user admin.
samba-samba-1  | passwd: unknown user admin
samba-samba-1  | New SMB password:
samba-samba-1  | Failed to find entry for user admin.
samba-samba-1  | Retype new SMB password:
samba-samba-1  | Failed to find user admin in passdb backend.
samba-samba-1  | >> ACCOUNT: adding account: admin to group: admin
samba-samba-1  | addgroup: unknown user admin
samba-samba-1  | >> VOLUME: adding volume: Backup (path=/shares/backup)
```

This type of error usually happens when wrong params are sent to `adduser`. I saw a commit in another samba repo that seems to fix a similar issue: https://github.com/dperson/samba/commit/e059b4f0fb9c7e916f83143ebab0945335e14207
Maybe this can help fix it here.

Thanks for your help!
