### ISSUE TITLE
Allow running the samba server not as root

### ISSUE THREAD

**Issue by wmoss** [ServerContainers/samba#82]
There are many ways to do this, but most of the containers I've run across that allow this have you set environment variables with the uid and gid that you'd like to use. For example,

```
services:
  samba:
    container_name: samba
    image: ghcr.io/servercontainers/samba
    restart: unless-stopped
    environment:
      UID: 1001
      GID: 1001

      SAMBA_CONF_LOG_LEVEL: 3
...
```
