### ISSUE TITLE
swarm mode not supported

### ISSUE THREAD

**Issue by svenczbg** [ServerContainers/samba#89]
Might be worth noting that the docker-compose.yml is limited in swarm mode due to the build-option. This is ignoired in swarm mode so the Dockerfile is not executed and wsdd/avahi don't work. 
Will do a PR if I succeed fixing this.

**Comment by MarvAmBass** [comment]
the docker-compose.yml is just an example, it's meant to be altered to your needs.

I don't see much of a problem of making it work with a docker-swarm configuration. I only don't see much of a benefit of running a samba fileserver in a distributed environment - I'm not sure, if it still works correctly behind a swarm load balancer

**Comment by alex-taxiera** [comment]
I'm currently using this container on a swarm node and it works fine.

here is my compose file (most of it anyway)

```
version: '3.7'

services:
  smbd:
    image: ghcr.io/servercontainers/samba
    hostname: samba
    deploy:
      replicas: 1
    environment:
      SAMBA_CONF_MAP_TO_GUEST: never
      SAMBA_GLOBAL_CONFIG_unix_SPACE_extensions: 'no'

      SAMBA_VOLUME_CONFIG_ADMIN: '[Admin]; path=/mnt/md0; read only = no; valid users = alex, debbie; admin users = alex, debbie;'
      SAMBA_VOLUME_CONFIG_PUBLIC: '[Public]; path=/mnt/md0/samba/public; read only = yes; valid users = debbie, fig, alex; admin users = alex; follow symlinks = yes; wide links = yes'
    ports:
      - target: 137
        published: 137
        mode: host
        protocol: udp
      - target: 138
        published: 138
        mode: host
        protocol: udp
      - target: 139
        published: 139
        mode: host
      - target: 445
        published: 445
        mode: host
    volumes:
      - /mnt/md0:/mnt/md0
      - /mnt/md0/samba/public:/mnt/md0/samba/public
    cap_add:
      - CAP_NET_ADMIN
```
