### ISSUE TITLE
Regular shares get affected by timemachine

### ISSUE THREAD

**Issue by alparr** [ServerContainers/samba#93]
I'm using timemachine withouth zeroconf, with a mix of shares. This is a simplified docker-compose setup:

```
  samba:
    image: ghcr.io/servercontainers/samba:smbd-only-latest
    container_name: samba
    environment:
      ACCOUNT_alpar: ...
      SAMBA_VOLUME_CONFIG_downloads: "[Downloads]; path=/shares/downloads; valid users = alpar; guest ok = no; read only = no; browsable = yes"
      SAMBA_VOLUME_CONFIG_timemachine: "[Timemachine]; path=/shares/timemachine; valid users = alpar; guest ok = no; read only = no; browsable = yes; fruit:time machine = yes"
    volumes:
      - /somepath/downloads:/shares/downloads:ro
      - /somepath/timemachine:/shares/timemachine:rw
    ports:
      - 445:445/tcp
    restart: unless-stopped
```

If I'm connecting to the timemachine share then the other "regular" shares get affected. I'm able to read and write to the root directory, but I'm not able to access any of the subdirectories.
<img width="372" alt="Screenshot 2023-07-08 at 17 23 14" src="https://github.com/ServerContainers/samba/assets/45291755/4f955e6b-ff09-41e9-8d0e-721cebd9b18d">

If I disconnect from everything and don't connect to the timemachine share then those other ones are also working. Is it not supported to have both regular and timemachine shares in the same container?
