### ISSUE TITLE
write access to folders owned by www-data

### ISSUE THREAD

**Issue by chriskisskiss** [ServerContainers/samba#96]
Hi, this is my docker-compose

```
version: '3'

services:
  samba:
    image: ghcr.io/servercontainers/samba
    container_name: samba
    restart: unless-stopped
    network_mode: host
    environment:
      USERID: 33
      GROUPID: 33
      SAMBA_CONF_LOG_LEVEL: 3
      SMB: 1
      ACCOUNT_alice: wunderland
      PERMISSIONS: 1
      SAMBA_VOLUME_CONFIG_shared_books: "[books]; path=/shares/books; valid users = alice; guest ok = no; read only = no; browseable = yes"
    volumes:
      - /etc/avahi/services/:/external/avahi
      - /books:/shares/books
    extra_hosts:
      - "host.docker.internal:host-gateway"
 ```
However, in folders owned by www-data:www-data (33:33) on host machine, I only have read permissions. I assumed setting USERID/GROUPID would solve the issue but id doesnt.
How can I solve this issue? It is not possible for me to change permissions on host folders.
Environment variables are successfully set (docker exec samba env).
www-data in alpine is displayed as xfs but also having ID 33 (docker exec samba id xfs -> uid=33(xfs) gid=33(xfs)).

Thank you very much
